/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tile_ifc_MyIfc */

#ifndef _Included_com_tile_ifc_MyIfc
#define _Included_com_tile_ifc_MyIfc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tile_ifc_MyIfc
 * Method:    createNativeIfc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tile_ifc_MyIfc_createNativeIfc
  (JNIEnv *, jobject);

/*
 * Class:     com_tile_ifc_MyIfc
 * Method:    readFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tile_ifc_MyIfc_readFile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_tile_ifc_MyIfc
 * Method:    to3DTiles
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tile_ifc_MyIfc_to3DTiles
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tile_ifc_MyIfc
 * Method:    setOutputPath
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tile_ifc_MyIfc_setOutputPath
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
