/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyIfc */

#ifndef _Included_MyIfc
#define _Included_MyIfc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyIfc
 * Method:    createNativeIfc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_MyIfc_createNativeIfc
  (JNIEnv *, jobject);

/*
 * Class:     MyIfc
 * Method:    readFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MyIfc_readFile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     MyIfc
 * Method:    to3DTiles
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_MyIfc_to3DTiles
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
